name: socially
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  google_fonts: ^2.1.0

  firebase_auth: ^3.1.3
  firebase: ^9.0.2
  cloud_firestore: ^2.5.3
  firebase_analytics: ^8.3.3
  firebase_core: ^1.7.0
  firebase_storage: ^10.0.5

  flutter_bloc: ^7.3.1
  equatable: ^2.0.3

  image_cropper: ^1.4.1
  image_picker: ^0.8.4+2
  cached_network_image: ^3.1.0+1

  intl: ^0.17.0
  timeago: ^3.1.0
  uuid: ^3.0.5


  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

